# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI5.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(370, 418)
        self.pushButton1 = QtWidgets.QPushButton(Form)
        self.pushButton1.setGeometry(QtCore.QRect(70, 30, 221, 41))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(Form)
        self.pushButton2.setGeometry(QtCore.QRect(70, 90, 221, 41))
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(Form)
        self.pushButton3.setGeometry(QtCore.QRect(70, 150, 221, 41))
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton4 = QtWidgets.QPushButton(Form)
        self.pushButton4.setGeometry(QtCore.QRect(70, 210, 221, 41))
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton5 = QtWidgets.QPushButton(Form)
        self.pushButton5.setGeometry(QtCore.QRect(70, 320, 221, 41))
        self.pushButton5.setObjectName("pushButton5")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(80, 270, 221, 31))
        self.spinBox.setMaximum(9999)
        self.spinBox.setObjectName("spinBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Training cifar10"))
        self.pushButton1.setText(_translate("Form", "1. Show Train Images"))
        self.pushButton2.setText(_translate("Form", "2. Show Hyperparameters"))
        self.pushButton3.setText(_translate("Form", "3. Show Model Structure"))
        self.pushButton4.setText(_translate("Form", "4. Show Accuracy"))
        self.pushButton5.setText(_translate("Form", "5. Test"))
